# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.2
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: 93330009+xxiled-plastic-cat@users.noreply.github.com
author_name: Xxiled
contract_name: burn_app
preset_name: starter
project_name: xnft-burn

